### ISSUE TITLE
Random crash when loading nodes list

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DPoSVoting#1]
## Current Behavior
When loading the nodes list, it seems like, randomly, it gets stuck and crashes the whole app (not just the dApp but elastOS app)

## Expected Behavior
Load nodes list without crashing

@BenjaminPiette

**Comment by chadracelis** [comment]
I tested this several times, but could never replicate the crash. Could of been something unrelated to the app, as elastOS while still under test goes through them from time to time. please let me know if this happens again, thanks
