### ISSUE TITLE
Can't vote again after closing wallet dApp

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DPoSVoting#2]
## Current Behavior
The user wants to vote for some nodes, click "Vote". Wallet dApp open. User didn't create a wallet and close the dApp wallet, user cannot vote anymore, loading/waiting spinner is showing - User has to exit and reload the dApp to vote again

## Expected Behavior
If the user cancels the wallet process by coming back to the dAPP dPosVoting, the Vote button should reset to his initial state

@BenjaminPiette

**Comment by chadracelis** [comment]
Fixed, thankyou
