### ISSUE TITLE
If nodes website link is http - it crashed the app

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DPoSVoting#3]
## Current Behavior
only https request are in the whitelist
if a node website candidate has a website with a http link (eg: http://sunnyfenghan.com - first in the list 😅) it crashed the app

## Expected Behavior
All nodes website candidates should be https

@BenjaminPiette

**Comment by BenjaminPiette** [comment]
Added to our PM tool thanks.

**Comment by chadracelis** [comment]
I removed direct link to node websites. thankyou
