### ISSUE TITLE
Difficult for the user to go back to the dApp after loading a node candidate website

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DPoSVoting#4]
## Current Behavior
When the user clicks on the link to a node candidate, it opens a webview - but it's difficult to go back right away to the dApp (user can navigate to a different link in the node candidate website, so he might have to click the back button several times)
- You can swipe from the top, a close button appears but it closes the dApp, not just the website 

## Expected Behavior
Add a close button and/or container with a close/back button to make it easy for the user to go back to the dApp

@BenjaminPiette

**Comment by chadracelis** [comment]
Removed node urls
